internetarchive/openlibrary-client

README.md

removing golang client

---

requirements.txt

addresses SSL_ST_INIT problems w/ pyOpenSSL 16.1.0

---

.travis.yml

@mekarpeles I don't have access to enable travis-ci but it's a good idea raised in #17 
Just getting the ball rolling with this simple starter yml . It'll most likely need the other dependencies installed before everything works nicely.

add initial travis file

---

olclient/openlibrary.py
olclient/schemata/edition.schema.json
olclient/schemata/work.schema.json
requirements.txt
tests/test_openlibrary.py

`save()` is in a very early stage, more work needs to be done on validation to be sure the json being written back to the server is good.

WIP: Edition JSON to match OL, JSON validation, and save()!

---

CHANGES
MANIFEST.in
olclient/__init__.py
olclient/cli.py
olclient/config.py
olclient/openlibrary.py
requirements.txt
tests/test_openlibrary.py

updated Open Library + client to use s3 keys if /account/login attempt json

Switching auth + config to use IA s3 keys (instead of user/pass)

---

olclient/cli.py

rm need to add --email to --configure; prompts automatically for email

---

olclient/openlibrary.py
tests/test_openlibrary.py

`save_many()`, as promised! ;)

add save_many, this closes #39

---

olclient/cli.py

m: fix typo in cli.py

---

olclient/openlibrary.py

@mekarpeles,  addressing your comments from my last PR!

handle key error and add docstring for new methods

---

.gitignore
README.md
examples/scripts/adding_a_new_book.py
olclient/openlibrary.py
tests/test_book.py

Closes #80 
1. README updated
2. Added a new example to add a book
3. Updated comments on how to add a new book

Documentation changes + Examples added

---

PULL_REQUEST_TEMPLATE.md

This PR closes #87 
In this Pull Request, file PULL_REQUEST_TEMPLATE.md was added in order to provide a skeleton for any future PR

Add missing PULL_REQUEST_TEMPLATE.md

---

olclient/openlibrary.py

This PR prevents an error under python3 when sending credentials

python 2 / 3 compatibility fix

---

olclient/common.py

This PR closes #103
I highly recommend using a more defined exception (ValueError is most appropriate here) but i have done it as requested in #103. hope its good!

implemented SuspiciousAuthorFormatException

---

olclient/openlibrary.py

This PR closes #142 
Basically replicate the Work.add_bookcover code. Tested; it works.

fix edition add_bookcover bug

---

requirements-dev.txt
requirements.txt

Update all Python dependencies except jsonpickle.  Upgrading jsonpickle causes our tests to fail.

Update all Python dependencies except jsonpickle

---

.travis.yml

Travis CI: Test Python 3.9.0

---

.travis.yml

https://www.python.org/downloads/release/python-390/

Travis CI: Use the released version on Python 3.9

---

.dependabot/config.yml
.github/dependabot.yml

Create dependabot.yml and delete .dependabot/configure.yml

---

examples/scripts/making_a_bot.py

__name__ should be a string
__name__ should be a string

Fixed typo in making_a_bot.py

---

README.md

Just documenting how to use keys directly based on [this](https://internetarchive.slack.com/archives/C0ETZV72L/p1628147190058200?thread_ts=1628097944.054200&cid=C0ETZV72L) slack message.
@BharatKalluri @cdrini 
Feel free to edit the wording and then merge

how to use keys directly

---

README.md

Add gol a go client in README.md file

---

.github/workflows/test_python.yml
olclient/entity_helpers/work.py

test_python.yml: Add codespell and add more flake8 and mypy tests

test_python.yml: Add codespell and add more flake8 and mypy tests

---

.github/workflows/test_python.yml
olclient/openlibrary.py
tests/schemata/test_import_schema.py

Closes #293
Add Windows to our GitHub Actions testing to replicate the 10 pytest failures reported in #293

Add Windows to openlibrary-client testing

---

olclient/openlibrary.py

Added a fn on edition to add cover from file

---

olclient/schemata/edition.schema.json

more schema additions

---

README.md

fixes #236
Links @BharatKalluri 's examples instead of the current unfinished colab.

better Google colab document link

---

olclient/__init__.py
olclient/cli.py
olclient/common.py
olclient/openlibrary.py

@scottbarnes Your review, please

openlibrary.py: Use absolute imports

---

.github/workflows/test_python.yml
olclient/schemata/edition.schema.json
olclient/schemata/import.schema.json

in line with 
https://openlibrary.org/help/faq/editing#publication-date

Specify EDTF in publish_date

---

requirements-dev.txt

Bumps the pypi group with 1 update: [pytest](https://github.com/pytest-dev/pytest).
Updates pytest from 8.0.0 to 8.0.1

Bumps the pypi group with 1 update: pytest

---

olclient/schemata/author.schema.json

Part of https://github.com/internetarchive/openlibrary/issues/10331

remove outdated Wikipedia field

---

.github/workflows/test_python.yml

Remove ruff job from CI; not working, and runs in pre-commit

---

olclient/schemata/author.schema.json

Part of https://github.com/internetarchive/openlibrary/pull/11100

remove location from authors schema
