internetarchive/openlibrary-client

olclient/openlibrary.py
TODO: maybe add a `delete()` to the `Work`, `Edition`, and `Author` classes?
Current usage:
```
from olclient.openlibrary import OpenLibrary
ol = OpenLibrary()
ol.delete('OL...W', 'Deleting Work')
==> <Response [200]>
ol.delete('OL...A', 'Deleting Author')
==> <Response [200]>
```
I'm using it to delete lists of olids with this code:
```
def delete_list(olid_list, comment):
for olid in olid_list:
r = ol.delete(olid, comment)
print "%s: %s" % (olid, r)
if r.status_code != 200:
print "%s response: %s" % (olid, r.content)
```
=> add delete by olid method and .json URL generator

.travis.yml, requirements.txt
This adds support for OS X to the CI build.
It needs a later version (1.8) of the cryptography package that includes binary wheels for this version of OS X to keep from having to build from source (which doesn't work due to misplaced headers), but I didn't see any reason for the hard pin to cryptography 1.5. 
This is another piece for #17
=> Mac OS X support for Travis CI build

olclient/openlibrary.py, olclient/utils.py, tests/test_openlibrary.py, tests/test_utils.py
Also adds the generic method `_merge_unique_lists`  from @cdrini which we have been using to merge works, in preparation for adding merge functionality to the client.
=> Adding subjects preserves order

olclient/schemata/edition.schema.json
`work_title` still exists on many OL Edition records, but there are more `work_titles`, and `work_titles` (plural) is consistent with other property names that are lists.
Any record that has a list `work_title` should have it converted to `work_titles`. I don't believe either of these fields are accessible via the UI. There is an `other_titles` property that appears on Librarian mode for editions, `work_titles` seems to be a work level `other_titles`?  Converting all `work_title` to `work_titles` feels like an easy first step before making sense of the multiple titles fields...
=> Improvements to Edition schema

olclient/schemata/edition.schema.json, olclient/schemata/work.schema.json
Both of these are "Kind: embeddable" from the descriptions at https://openlibrary.org/type/author_role and https://openlibrary.org/type/link  as such they should have `type` set with the format `"type": { "key": "/type/<type>"}`. Updating the json schema for both to reflect this.
Unfortunately in the current work data for author_roles, there is a pretty even mix of `type` styles:
`"authors": [{"type": "/type/author_role"`   => **8,280,196**
vs
`"authors": [{"type": {"key": "/type/author_role"}`  => **7,743,184**
'links` in works are fully consistent, all use the "type: key:" style, I used that as the model for how an OL embeddable type should be.
=> Fix author_roles defn. Add links

MANIFEST.in, olclient/openlibrary.py, olclient/schemata/edition.schema.json, olclient/schemata/shared_definitions.json, olclient/schemata/work.schema.json, tests/test_openlibrary.py
@cdrini good suggestion, and I was able to do the sharing it with relative paths!
I'm not sure whether the structure and naming of `shared_definitions.json` is good enough.. it's just a very simple json file containing the definitions at the top level with a `"$schema": "http://json-schema.org/draft-04/schema#"` (which seems to validate).  Second opinions very much welcome :)
My justification for the current naming and structure is to reduce the length of the `$ref`s , so no `shared_definitions.schema.json` and no `#definitions/<definition>`
=> Shared definitions file for schemata, closes #51

olclient/openlibrary.py, tests/test_openlibrary.py
There are a few things in this PR, the last features I needed to get the client reliable and usable for some real data fixing.
1. Adding Redirect and Delete classes so olids can be converted and saved back as `/type/delete` or `/type/redirect` (essential for merging!)
2. Created `Work.add_author()` to conveniently associate authors with works in the correct format.
**TODO:** 
* method to remove authors
* ability to set optional `role` and `as` properties that are present in the schema
3. Better exception handling
**TODO** 
* add some tests
* review all OL classes to ensure they have the same exception handling, refactor common code
4. handle `/type/text` properties consistently on save.
**TODO**
* Investigate root cause for why OL / Infogami saves `/type/text` inconsistently 
* refactor …
=> Add Redirect+Delete classes. Work.add_author(). Exception handling, and handle /type/text

setup.cfg
Edit setup.cfg in order to exclude virtualenv directories when running test.py
=> Fixes #82: Update setup.cfg in order to exclude dirs

.travis.yml
This PR closes #93
mac osx has been failing due to incomplete travis CI instructions. Dropping support until fixed.
=> fix ci by rm incomplete mac os checks

README.md
This PR does not close an existing issue
To install, we also need python-dev or python3-dev
Also making formatting of docs slightly more consistent
=> DOCUMENTATION: Include the need for python-dev

olclient/common.py
This PR closes #98 
It's easy to accidentally misformat entity identifier dicts. This PR adds some basic validation to make it a bit harder.
```bash
adamreis@Adams-MacBook-Pro ~/G/d/openlibrary-client>
python3 -m olclient.cli --create "{\"title\":\"All We Ever Wanted: A Novel\", \"author\": \"Emily Giffin\", \"identifiers\":{\"isbn_10\": \"0399178929\"}}"
Traceback (most recent call last):
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/adamreis/Google-Drive/dev/openlibrary-client/olclient/cli.py", line 116, in <module> …
```
=> Validate identifiers when creating Entities

olclient/openlibrary.py, tests/test_openlibrary.py
This PR closes #60, #29, and #71 
Uses `requests.raise_for_status()` http://docs.python-requests.org/en/master/_modules/requests/models/#Response.raise_for_status  to raise `HTTPError` on statuses greater 400, therefore preventing 404s and 50x responses creating blank or error items that can be saved.
Also, after some refactoring to add a single location to handle GET requests to OL, `_get_ol_response()`, this will attempt retries on non 4xx errors (e.g. 500s), but raise ``HTTPError` exceptions immediately on requests that result in Not Founds.
I am trying to make the logic so that a direct request for an OLID that results in a 404 Not Found raises a requests Exception, but anything that is _searched for_ by some term or other non-OL bibliographic key can return `None`.
There may still be …
=> fixes #60 and related by raising HTTPErrors

olclient/openlibrary.py
@mekarpeles In order to make this work I'm using the following code locally:
```
from olclient.openlibrary import OpenLibrary
from collections import namedtuple
Credentials = namedtuple('Credentials', ['username', 'password'])
c = Credentials('openlibrary@example.com', 'admin123')
ol = OpenLibrary(base_url='http://localhost:8080', credentials=c)
```
There is probably a neater way to integrate this, but creating the `namedtuple` seemed the easiest way to interface with the existing methods.
The first commit in this PR "direct check for session cookie" is good though as it directly check whether we have a cookie. Previously it got confused with redirects, where the cookie had been set, but the last response in the redirect chain did not so the check failed, even though the session knew …
=> WIP: Allow openlibrary-client to auth with locally running openlibrary dev env

olclient/openlibrary.py
This PR closes #101 
The method stub `json_to_book` in the Edition class is deprecated and can be removed
=> Remove deprecated json_to_book method stub in Edition

README.md, requirements.txt
This PR closes #117 
and closes #110 
I have tested this on under python 2.7 and 3 by install from the repo in fresh Ubuntu Xenial docker containers. Neither had `openssl-dev` or `libssl-dev` so I think these removals are safe, and will hopefully make installation simpler.
=> Tidy requirements by removing transitives

setup.py
This PR updates the package repo URL from
url='https://github.com/ArchiveLabs/openlibrary-client',
to
url='https://github.com/internetarchive/openlibrary-client',
Looks like ownership was transferred from https://github.com/ArchiveLabs to https://github.com/internetarchive for this repo. This updates the setup.py info to avoid the redirect.
=> correct repo url

README.md
Quick fix to the code example for `Author` in the README.
=> Fix Author code example in README.md

.travis.yml
[Travis are now recommending removing __sudo__](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)
=> Travis CI: Add Python 3.7 to the testing in allow_failures mode

olclient/openlibrary.py
The valid identifier error and rejection message should only be for creating new books, not prevent the client from loading existing data from Open Library (otherwise there is no way to check and repair issues!)
=> Don't reject existing OL edition data when getting books

olclient/cli.py
This PR closes #119 
Previously CLI invocation missing config files would mean a `ValueError("No cookie set")` being flagged.
This PR covers this behaviour by the use of a try-except block included in `olclient/cli.py` which prompts the user with instructions(configure option example) to configure the olclient and displaying the general usage of the ol command. 
The prompt displayed is:
> Seems like you haven't configured your olclient with credentials.
You can configure using the following command:
$ol --configure --email \<EMAIL\>
=> Replace ValueError with prompt to configure on first usage

olclient/common.py, olclient/openlibrary.py
This PR closes #118 
Check the commas present in the author name in the retrieved data from the respective endpoint(associated with the function that initiates the `Results.Document` object creation) before the creation of the Author object. 
Doing this check before the creation of the `Author` object is necessary to avoid triggering the comma check in the `Author`'s `__init__` which is in place to avoid author names with commas being written into the database. It was this unintended check on data already in the database(while retrieving) which was causing the issue
=> Don't reject author data with comma during retrieval 

olclient/cli.py, olclient/openlibrary.py
This PR closes #131
The newly added `get_works` function is a wrapper to access the following endpoint
```
https://openlibrary.org/authors/<Author OLID>/works.json
```
which returns the list of `Works` associated with an `Author` in JSON format.
All the information field present for a Work is returned.
The following is the function signature information for `get_works` function:
> **Args**:
_olid_ (unicode) - OpenLibrary ID for author to search within
Open Library's database of authors to retrieve his Works.
_name_ (unicode) - name of an Author to search for within OpenLibrary.
_limit_ (integer) - number of Author's Works to return.
**Returns:**
A (list) of Works from the OpenLibrary associated with the
Author.
=> Feature addition to list the works of a particular Author

olclient/common.py, olclient/openlibrary.py
directly when loading authors
Rejecting Author names with commas when creating new authors (via common.Author) is appropriate (with some caveats that have been mentioned elsewhere) since OL standard requires natural name order, but this should _not_ prevent the ol-client from loading existing authors with commas. Otherwise, how could they be fixed using the ol-client?
This PR fixes this problem. Previously 
```
from olclient.openlibrary import OpenLibrary
ol = OpenLibrary()
a = ol.get('OL69006A')
```
resulted in:
```
ValueError: Smith, John is not a valid Author name - No commas allowed (first last)
```
and `a` set to `None`
After this PR, the `Smith, John` author can be loaded normally and either inspected without modification, or corrected etc.
=> don't reject existing OL author names with commas

.travis.yml, olclient/common.py, olclient/openlibrary.py, olclient/utils.py, requirements.txt, tests/test_marc.py, tests/test_openlibrary.py
* Add Python 3.7 and 3.8 to the testing
* Travis CI: Drop support for EOLed Ubuntu Trusty
* PEP 479: Fix StopIteration for Python >= 3.7
* https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app
* unittest.TestCase.assertEquals() -->assertEqual()
* Fix DeprecationWarning: invalid escape sequence \d
* Fix pytest deprecation: "message" parameter of pytest.raises
* https://docs.pytest.org/en/latest/deprecations.html#message-parameter-of-pytest-raises
* Fix typos found by codespell
*  programatically --> programmatically
*  Exension --> Extension
=> Support Py37 & Py38 and drop EOLed Ubuntu Trusty

.travis.yml
Current and one point version back should be sufficient.
=> Don't need so many Python 3 versions on Travis

olclient/config.py
This PR closes #168
On line 132 of `config.py` the following check is performed:
```config['s3'] = Credentials(access, secret) if (access, secret) else None```
I'm assuming the goal is here to check if `access` and `secret` are set and then login with these credentials. The problem though is that, this statement actually only checks if the tuple contains any values, not if they are both truthy.
My fix is to surround the tuple with a call to `all()`. One could also consider using `any()` (or just `if access`), but I don't think there would be a use case where the secret is empty.
=> Fix truthiness check in config.py

.travis.yml, README.md, setup.py
Closes #193
There might still be some residual code with py2/3 code, but no longer test on/say that we support py 2
Pulled the minimal set of changes from #180
Note:
- This is blocking #178
=> Remove Python 2 support

requirements.txt
Fixes #155
https://gitlab.com/pymarc/pymarc/-/tags
The Python type hints that we are putting into pymarc should improve our ability to detect type errors in Python 3.
=> Upgrade pymarc on Python 3 only

olclient/openlibrary.py
This PR closes https://github.com/internetarchive/openlibrary-client/issues/219
Follows next link if present while populating editions
```python
import olclient
open_library = olclient.OpenLibrary()
work = open_library.Work.get(u'OL495934W')
editions = work.editions
print(len(editions)) # now returns 184 instead of 50
```
=> Follow next link while populating editions for work

olclient/cli.py
This PR closes https://github.com/internetarchive/openlibrary-client/issues/215
We should be writing to stdout if the cli tool succedes.
`argparse`'s `print_help` (which we use in `cli.py`) uses `sys.stdout.write` too
https://github.com/python/cpython/blob/d35eef3b904b62e9c775bf3764ab0a0611f5a860/Lib/argparse.py#L2545-L2548
=> Send success output of cli to STDOUT

examples/scripts/making_a_bot.py, olclient/bots.py, requirements-dev.txt
This PR closes #237
Limit parsing was not functional because the definition of the flag was incorrect. This fixes it.
=> Fix limit parsing in AbstractBotJob

olclient/entity_helpers/work.py, olclient/openlibrary.py, olclient/utils.py
This PR closes #234
Deleting work along with its editions is something done very often in bots, this helps by making sure the work is deleted if and only if the editions are deleted as well
=> Added delete fn on work

MANIFEST.in
Before updating MANIFEST.in
```
(venv) (base) ➜  openlibrary-client git:(master) pip install .
(venv) (base) ➜  openlibrary-client git:(master) cd venv/lib/python3.9/site-packages/olclient
(venv) (base) ➜  olclient git:(master) ls
__init__.py  __pycache__  bots.py  cli.py  common.py  config.py  openlibrary.py  schemata  utils.py
```
`entity_helpers` and `helper_classess` are not currently packaged at this point.
```
(venv) (base) ➜  openlibrary-client git:(fix/add_folders_manifest_json) pip install . 
(venv) (base) ➜  openlibrary-client git:(fix/add_folders_manifest_json) cd venv/lib/python3.9/site-packages/olclient
(venv) (base) ➜  olclient git:(fix/add_folders_manifest_json) ls
__init__.py  __pycache__  bots.py  cli.py  common.py  config.py  entity_helpers  helper_classes …
```
=> Added recently added folders to MANIFEST.in

olclient/bots.py, tests/test_bots.py
This PR closes #241 
Basically #241 with store_true + backwards compatability . Tested locally for the basic case
=> AbstactBotJob: use write changes instead of dry_run + store_true

olclient/schemata/import.schema.json
Adds optional `identifiers` field to our import object schema.  `identifiers` is an object that maps lists of stings to a string key.
=> Add identifiers to import schema

olclient/schemata/import.schema.json
This adds `cover` property to our import schemata.
This is in support of https://github.com/internetarchive/openlibrary/issues/5993
=> Add cover URL to import schema

olclient/__init__.py
The code on the repo is later than, not earlier than the code on PyPI.
Currently [`pipx`](https://pypi.org/project/pipx) installing from the repo is ___v0.0.20___ but the [Oct 2020 release on PyPI](https://pypi.org/project/openlibrary-client) is ___v0.0.30___.
$ `pipx install openlibrary-client`
```
installed package openlibrary-client 0.0.30, installed using Python 3.9.13
```
$ `pipx install git+https://github.com/internetarchive/openlibrary-client.git`
```
installed package openlibrary-client 0.0.20, installed using Python 3.9.13
```
$ `pipx install git+https://github.com/internetarchive/openlibrary-client.git@olclient.__version__-=-0.0.31`
```
installed package openlibrary-client 0.0.31, installed using Python 3.9.13
```
=> Upgrade olclient.__version__ which is < pypi version

olclient/bots.py, olclient/common.py, olclient/entity_helpers/work.py, olclient/openlibrary.py, tests/test_book.py, tests/test_openlibrary.py
Use [`pyupgrade --py37-plus --keep-runtime-typing **/*.py`](https://pypi.org/project/pyupgrade) and [`flynt .`](https://pypi.org/project/flynt) to convert to Python f-strings which are easier to read and faster.  https://www.scivision.dev/python-f-string-speed
=> Convert to Python f-strings for speed.

olclient/cli.py
This PR closes #322 . I would usually wait for the release, but this is a pretty big P0 since openlibrary-client is entirely broken!
=> Fix configure failing until next release of ia tool

README.md
* Replace the Travis CI badge with GitHub Actions badges
* Add support for Python 3.10 to match `setup.py`
* Add pipx installation instructions
* Update usage text
=> README.md: Update usage text

README.md
https://pypa.github.io/pipx/#installing-from-source-control Replaces the current three-step installation process with a single-step process and keeps `ol` in its own virtualenv that can be upgraded anytime with `pipx upgrade-all`
=> pipx install git+https://github.com/internetarchive/openlibrary-client

olclient/schemata/edition.schema.json, olclient/schemata/import.schema.json
This PR closes #342 
Correct the edition schema `languages` field name (#135 )
Adds `translated_from` and `translation_of` fields to the edition schema and import schema.
=> Languages schema updates

README.md
The `ol` command  line utility does, in fact, do something.
=> Remove misleading statement from README

README.md
This hasn't been vetted by anyone yet, but was mentioned during our community call today.
Linked repo: https://github.com/Luca3317/OpenLibrary.NET
**Edit:** Should we ask Luca3317 before adding their library to the README?
=> Add C# library to README

README.md
Add documentation for using `openlibrary-client` to authenticate against the local development environment, and also add a line about installing from the `master` branch using ordinary `pip`.
=> Documentation: add local dev authentication steps
